// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyPN2AI802ei39j8DNoxrT8y8qYu1lgRA',
    appId: '1:142876190817:web:4daebf75c8876f609f6220',
    messagingSenderId: '142876190817',
    projectId: 'prognosify-63e02',
    authDomain: 'prognosify-63e02.firebaseapp.com',
    storageBucket: 'prognosify-63e02.appspot.com',
    measurementId: 'G-J3QK2YH1EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXxs2Mr7A1ezKUL0tJpS1233kQxfluoWc',
    appId: '1:142876190817:android:d0139cffe97de30f9f6220',
    messagingSenderId: '142876190817',
    projectId: 'prognosify-63e02',
    storageBucket: 'prognosify-63e02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaUrAU9-cehDnWxM21dTEpyXpey6luPIk',
    appId: '1:142876190817:ios:fce227c1485c31f69f6220',
    messagingSenderId: '142876190817',
    projectId: 'prognosify-63e02',
    storageBucket: 'prognosify-63e02.appspot.com',
    iosClientId: '142876190817-rirke8kkvad6p0srjjdrpdsbgemjmboc.apps.googleusercontent.com',
    iosBundleId: 'com.example.prognosify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaUrAU9-cehDnWxM21dTEpyXpey6luPIk',
    appId: '1:142876190817:ios:1bd4f485dfcb299f9f6220',
    messagingSenderId: '142876190817',
    projectId: 'prognosify-63e02',
    storageBucket: 'prognosify-63e02.appspot.com',
    iosClientId: '142876190817-p21dq9qmn55u78nenu2je0ubclg5gqnq.apps.googleusercontent.com',
    iosBundleId: 'com.example.prognosify.RunnerTests',
  );
}
